<?php
/**
 * Author: boolean
 * Email: boolean.wang@foxmail.com
 * Date: 2017/4/14 22:48
 */

namespace frontend\assets;

use yii\web\AssetBundle;

class BaseAsset extends AssetBundle
{
    /**
     * 公共版本号
     * @var
     */
    public $version = 'v12';
    /**
     * 公共依赖源
     * @var string
     */
    public $sourcePath = '@resource';
    /**
     * 公用依赖关系
     * @var array
     */
    public $depends = [
        'frontend\assets\AppAsset',
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (!empty($this->css) && is_array($this->css)) {
            $cssArr = $this->css;
            $this->css = '';
            foreach ($cssArr as $css) {
                $this->css[] = $css . '?ver=' . $this->version;
            }
        }
        if (!empty($this->js) && is_array($this->js)) {
            $jsArr = $this->js;
            $this->js = '';
            foreach ($jsArr as $js) {
                $this->js[] = $js . '?ver=' . $this->version;
            }
        }
    }
}